package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* Thursday, November 30, 2023 9:21:38 AM WAT
*/

public interface IConversionRemoteOperations 
{
  double convertirMontant (double mt);
} // interface IConversionRemoteOperations
